### ISSUE TITLE
the audio type required in this code?

### ISSUE THREAD

**Issue by hithzf** [charlesconnell/AudioCompare#4]
when i invoke 'python main.py -f xx.wav -f xx.wav' , there comes an error `AttributeError: 'TypeError' object has no attribute 'message'`

**Comment by charlesconnell** [comment]
Could you please provide the full stacktrace?

**Comment by hithzf** [comment]
`Traceback (most recent call last):
  File "H:\pycode\har\code\python\AudioCompare-master\Matcher.py", line 105, in
_file_fingerprint
    file = InputFile(filename)
  File "H:\pycode\har\code\python\AudioCompare-master\InputFile.py", line 28, in
 __ init __
    self.wav_file = open( filename, 'r' )
TypeError: expected str, bytes or os.PathLike object, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 45, in <module>
    exit(audio_matcher())
  File "main.py", line 33, in audio_matcher
    results = matcher.match()
  File "H:\pycode\har\code\python\AudioCompare-master\Matcher.py", line 324, in
match
    dir1_results = _file_fingerprint(dir1_files)
  File "H:\pycode\har\code\python\AudioCompare-master\Matcher.py", line 136, in
_file_fingerprint
    return FileErrorResult(e.message)
AttributeError: 'TypeError' object has no attribute 'message'`

**Comment by charlesconnell** [comment]
The latter half of this should be solved: I think it was an incorrect assumption that all Exceptions have message attributes.

However, this does not solve your real issue. I'm not yet able to reproduce that.
